# docker-compose.yml
version: '3.8'

services:
  # Serviço da API FastAPI
  mustafa_api: # <-- NOME ALTERADO
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code # Mapeia o código para hot-reload
    env_file:
      - .env # Carrega as variáveis de ambiente
    depends_on:
      - mustafa_postgres # <-- DEPENDÊNCIA ALTERADA
    networks:
      - mustafa_network # <-- REDE ALTERADA

  # Serviço do Banco de Dados PostgreSQL
  mustafa_postgres: # <-- NOME ALTERADO
    image: postgres:15
    volumes:
      - mustafa_postgres_data:/var/lib/postgresql/data/ # <-- VOLUME NOMEADO ALTERADO
    environment:
      POSTGRES_USER: ${DB_USER}       # Lê do .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Lê do .env
      POSTGRES_DB: ${DB_NAME}           # Lê do .env
    # A porta 5432:5432 foi removida.
    # É uma boa prática não expor a porta do DB diretamente para a máquina host
    # se apenas o container da API precisa acessá-la. A comunicação será via rede interna do Docker.
    # Se você precisa acessar o DB com um client (DBeaver, etc), descomente a linha abaixo.
    # ports:
    #   - "5432:5432"
    networks:
      - mustafa_network # <-- REDE ALTERADA

# Define o volume persistente para os dados do Postgres
volumes:
  mustafa_postgres_data: # <-- NOME ALTERADO
    driver: local

# Define a rede interna para os serviços se comunicarem
networks:
  mustafa_network: # <-- NOME ALTERADO
    driver: bridge